### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by michaelmowry** [stakelink/substrate-payctl#20]
Traceback (most recent call last):
  File "/usr/local/bin/payctl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/payctl/payctl.py", line 191, in main
    cmd_pay(args, config)
  File "/usr/local/lib/python3.8/dist-packages/payctl/payctl.py", line 70, in cmd_pay
    eras_payment_info = get_eras_payment_info_filtered(
  File "/usr/local/lib/python3.8/dist-packages/payctl/utils.py", line 98, in get_eras_payment_info_filtered
    eras_payment_info = get_eras_payment_info(substrate, start, end)
  File "/usr/local/lib/python3.8/dist-packages/payctl/utils.py", line 68, in get_eras_payment_info
    eras_rewards_point = get_eras_rewards_point(substrate, start, end)
  File "/usr/local/lib/python3.8/dist-packages/payctl/utils.py", line 23, in get_eras_rewards_point
    reward_points = substrate.query(
  File "/usr/local/lib/python3.8/dist-packages/substrateinterface/base.py", line 1316, in query
    obj.decode()
  File "/usr/local/lib/python3.8/dist-packages/scalecodec/base.py", line 658, in decode
    self.value_serialized = self.process()
  File "/usr/local/lib/python3.8/dist-packages/scalecodec/types.py", line 471, in process
    field_obj = self.process_type(data_type, metadata=self.metadata)
  File "/usr/local/lib/python3.8/dist-packages/scalecodec/base.py", line 740, in process_type
    obj = self.runtime_config.create_scale_object(type_string, self.data, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/scalecodec/base.py", line 156, in create_scale_object
    return decoder_class(data=data, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/scalecodec/types.py", line 1669, in __init__
    sub_type_parts = [x.strip() for x in self.sub_type.split(',')]
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by apuigsech** [comment]
Fixed on PR #17.
